### ISSUE TITLE
Upgrade autosuggest to new widget

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1326]
Consistently use the new autosuggest widget for:

Report Editing
- [x] authorization groups ( templates: all, recent)
- [x] tasks ( templates: all, recent, assigned to my org, assigned to org of report)
- [x] locations ( templates: all, recent)

Org editing
- [x] parent org (templates: all + something we still needs to refine)
- [x] approver position (templates: all advisor positions, colleagues)
- [x] tasks ( templates: all, assigned to my org)

Position editing
- [x] org (templates: all + something we still needs to refine)
- [x] location (templates: all)

Authorization group editing
- [x] positions (templates: all => {status: Position.STATUS.ACTIVE, type: [Position.TYPE.ADVISOR, Position.TYPE.SUPER_USER, Position.TYPE.ADMINISTRATOR], matchPersonName: true})

Task editing
- [x] responsible organization
- [x] parent task fields

Merge people
- [x] person 1
- [x] person 2

Show person page
- [x] edit associated positions modal
- [x] assign position modal

Show position page
- [x] edit associated positions modal
- [x] assign person modal

Advanced search for reports
- [x] author
- [x] attendee
- [ ] pending approval of
- [x] author position
- [x]  attendee
- [x]  position
- [x] location
- [x] tag
- [x] task
- [x] organization

Advanced search for people 
- [x] organization
- [x] location

Advanced search for positions 
- [x] organization
- [x] location

Advanced search for tasks
- [x] organization

**Comment by maradragan** [comment]
The new widget should also be used for:
- authorization group editing => positions field
- task editing => responsible organization and parent task fields
- merge people => in order to select the duplicate person
- assign position overlay =>select position
- assign person overlay => select person
- advanced search => organization filter
- advanced search for reports => author, attendee, pending approval of, author position, attendee position, location, tag, task
- advanced search for people => location
- advanced search for positions => location
