### ISSUE TITLE
Add saved searches pagination

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#15]
"When using ""Saved searches,"" the user can only view the first 10 records.  The search results are not paginated.  Using a regular search, the user can view all the search results using pagination.
Reference item 2

**Comment by gjvoosten** [comment]
The proposed approach is:
- make saved searches use the regular Search/AdvancedSearch (so selecting a saved search will take you to a new page, behaving just as if you had done a regular search)
- show all relevant results instead of only reports (again, just like a regular search)
- build a component that shows the top 10 results of the default saved search on the homepage (dashboard-like functionality)

**Comment by gjvoosten** [comment]
The proposed approach does not fit very well with the current architecture. Instead the behaviour on the home page will stay the same (for now), but there will be an extra button that takes you to the search page with the saved search. That allows you to see more results (of different object types, paginated etc.), and also to refine your saved search.
