### ISSUE TITLE
End of tour date does not populate when selecting from the calendar picker

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1528]
1. Create a new person (advisor or principal)
2. Click in the end of tour date data field; Result: the calendar picker is displayed
3. Click the ">" button to advance the month to any month in the future
4. Click on a date in the future month; Result: the calendar picker is no longer displayed and the end of tour date is not populated.

The end of tour date does populate if the month is not changed.
1. Create a new person (advisor or principal)
2. Click in the end of tour date data field; Result: the calendar picker is displayed
3. Click on a date in the current month: Result: the calendar picker is no longer displayed and the end of tour date is populated

**Comment by dspCarlson** [comment]
This bug also applies to the calendar picker in engagement reports.  The end of tour date only populates if the date chosen is in the current month displayed.  Choosing a month before or a month after and the date chosen is not displayed in the end of tour date.

**Comment by dspCarlson** [comment]
This bug also applies to the calendar pickers that are in the filtered searches.

**Comment by gjvoosten** [comment]
It looks suspiciously like this bug: https://github.com/palantir/blueprint/issues/3340 , but the fix for that (since https://github.com/palantir/blueprint/wiki/3.x-Changelog#blueprintjsdatetime-371 ) is already in the release. However, under IE11 / Win7 I can indeed reproduce the problem: the first click after changing the month does *not* pick a date. So it would appear to be an IE11-specific issue.

**Comment by gjvoosten** [comment]
Probably this one: https://github.com/palantir/blueprint/issues/2924 which is still open.
