### ISSUE TITLE
Report showing the number of not approved reports

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#155]
This report is crucial for super users and administrators to be able to identify when reports are getting stuck in the approval process: 
## Essential features:
* Must show graphically and in numbers how many reports have not been approved 15 days after their engagement date.
* Must be sortable by organisation.
## Desirable features:
* Be able to drill down to the individual approver the report is stuck with.

## Example
on request

## Implementation
It counts - per advisor organisation - the reports pending approval which have been submitted up till the selected date. The default date is DAILY_ROLLUP_MAX_REPORT_AGE_DAYS plus one day in the past.

**Comment by VassilIordanov** [comment]
![image](https://user-images.githubusercontent.com/16674032/29820271-484238a8-8cc4-11e7-9e15-c3ea3e010a83.png)

**Comment by maradragan** [comment]
Are the users interested only in the reports which have not been approved yet and it is alrwady >= 15 days since they were submitted?

Or do they want to know in general for how many reports  it takes at least 15 days to be approved?

**Comment by VassilIordanov** [comment]
@maradragan It is item 1. In this particular case, they want to police the workflow and want to know the current reports that are past due

**Comment by dspCarlson** [comment]
@gjvoosten  @maradrag Is the default 15-day cut off value hard-coded?  If possible, could you make the cutoff value based on the value in adminSettings.key = DAILY_ROLLUP_MAX_REPORT_AGE_DAYS plus one day?  If 15 days is hard-coded and a change of leadership determines 15 days is too many days, we will want to change the default cut off number of days.  If default cut off date is based on the DAILY_ROLLUP_MAX_REPORT_AGE_DAYS the change in the date picker default value would be controlled on our end instead of being hard-coded.

**Comment by gjvoosten** [comment]
@dspCarlson The 15 days default is currently hard-coded (but the date is selectable). Would the default setting always be _rollup days plus one_, or are the two settings potentially independent? Because in that case we may decide to move the default to the `dictionary.json` which we are currently making deployment-specific (but putting the definition inside the `anet.yml` configuration file).

**Comment by dspCarlson** [comment]
@gjvoosten The DAILY_ROLLUP_MAX_REPORT_AGE_DAYS is not only the rollup variable, but also represents the threshold for meeting the release requirement.  If a report is released but released too late for the daily rollup, the advisor organization has not met the release requirement.  So when a super wants to know which reports have not met the release requirement, by default they should see the reports that have not met the daily rollup release requirement, i.e. DAILY_ROLLUP_MAX_REPORT_AGE_DAYS + 1.  The DAILY_ROLLUP_MAX_REPORT_AGE_DAYS variable is an arbitrary time period that could be changed with any change of leadership.  That's it was made a variable and not hard-coded.

**Comment by maradragan** [comment]
I found a bug today, changing the date no longer updates the chart, I am working on it.
