### ISSUE TITLE
Do not use Zulu time in the downloadable spreadsheet

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1569]
Just downloaded a spreadsheet after conducting a filtered search.

The times in the spreadsheet are in Zulu.  All operations are conducted in local time here.  Zulu is used for military operations that span multiple time zones.

People will be miserable if they have to use Zulu time.

Please do not use Zulu time in ANET.

**Comment by gjvoosten** [comment]
@dspCarlson Which time zone _would_ you like to use? Because the server has no way of knowing which time zone the user would like to see. We could make a (read: *one*) time zone configurable through `anet.yml`, and that will apply to any server-side rendered output, like emails or Excel export; currently it is hard-coded to `UTC`.

(Note that on the browser side it is different, as there the browser's locale can be used [and that might vary per user]).

**Comment by dspCarlson** [comment]
@gjvoosten The time zone should be the local time.

**Comment by VassilIordanov** [comment]
Excel exports should _always_ be in absolute time/date, exporting a local date is a bad idea. The two options are:
 - keep iso8601 dates (as it is now) and handle the conversion with an excel formula as expressed here: iso8601
- output the native 64 bit float that excel expects by using http://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/DateUtil.html#getExcelDate-java.util.Date-
