### ISSUE TITLE
Report "attended and submitted"

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#159]
One organization currently complies by hand a table of the engagements attended by their advisors and the number of engagement reports that they submit over a week.  This is a very useful management tool for them, automating it would save their staff several hours of work a week.  

Visible only to super users and admins at this time
## Essential:
* Must be sortable by organisation and displayed in tabular format.
## Nice to have
* export to CSV/EXCEL functionality
## Examples:
on request

**Comment by VassilIordanov** [comment]
Answering @evdhoudt 's slack questions here, so that @dspCarlson can also take a look:
Q: What date should be used for the submitted reports? Since there is no submitted_at date. At the I use the created_at date for the grouping. 
A: created_at is good
Q: Should all report states be included?
A: I would say yes
Q: What report state should be filtered by to get engagements attended? At the moment I use report state RELEASED. However, when a report is in DRAFT or anything else except cancelled, the engagement could still have gone trough… 
A: I would say it can be in DRAFT or in any state except cancelled. @dspCarlson , can you confirm please
Q: Basically the question is, how are the reports currently compiled so we are able to reproduce the same statistics?
A: I'll try to figure it out, @dspCarlson  - any ideas?

**Comment by dspCarlson** [comment]
Q: What date should be used for the submitted reports? Since there is no submitted_at date. At the I use the created_at date for the grouping and past the DRAFT state.
A: I agree with @VassilIordanov The created_at field is the only field to use because there is not a submitted_at field.  On our side there is proposal (item 88) to create a submitted_at field.  The users are asking for this date to keep report authors accountable.

Q: Should all report states be included?
A: Yes.  There is a future issue and a past issue to resolve with reports.  Future Issue: Which approver(s) need to approve the report? They are holding up the report being released.  Past Issue: Who approved the report and when?  Approvers sometimes approve the wrong report or the approvers take too long to approve.  Approval chain steps can have 20 people because each organization is only allowed one approval chain yet different approvers need to approve different type of reports.

Q: What report state should be filtered by to get engagements attended? At the moment I use report state RELEASED. However, when a report is in DRAFT or anything else except cancelled, the engagement could still have gone trough…
A: I agree with @VassilIordanov Cancelled and Draft states should not be included in engagements attended.

Q: Basically the question is, how are the reports currently compiled so we are able to reproduce the same statistics?
A: There are two scenarios I can think of:  Scenario 1: Organizations want to know how many reports were written (draft, pending or released) during a given period of time and then compare to how many actual engagement there were during the same period of time.  Scenario 2: Organizations want to know how many reports were released during a given period of time.  Believe it or not, organizations compare themselves to other organizations.  It's almost like the organizations have a competition among themselves.
