### ISSUE TITLE
Need to know engagements

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#165]
-- Updated requirement ---

Provide a mechanism to handle sensitive information.

Suggested approach:

# Phase 1
Add an optional sensitive information text field to each report.
Information entered in that box should be visible only to authorized personel.

Define autorized personel as the following:
for each org, provide a list of default "sensitive information handling personel"
If and only if a reader is the report's author or is part of that group, he/she can have access to the sensitive content of reports from the same organization

#Phase 2
Provide a mechanism to override the default list on a report-by-report basis, i.e. exlude or include individual members for this report only

**Comment by VassilIordanov** [comment]
Scratchpad for proposed solution

## Case 1. Nested explicit restrictions
An engagement report is visible to the user if:
  - the user is an admin
  - the user is the report author
  - the primary advisor of the report belongs to an org that is not restricted, neither is any of its parent orgs
  - the primary advisor of the report belongs to an org that that is restricted or has a restricted parent _and_ the user is member of the most specific of these restricted org (or an indirect member thorugh a sub org)

### Pros: relatively flexible
### Cons: may be trickier to explain

### HMI:
Any org has :
- an indication of it's parent's most specific restriction (if any). Example: this org (1.1.1) is a sub organization of the restricted org 1.1
- or an indication of a locally defined restriction. Example: this org restricts access to its members

### Db:
Each org has a "restricted" field which can be true or false

## Case 2. Flat restrictions

restricted here has a slightly different meaning

An engagement report is visible to the user if:
  - same first 3 cases as above
  - the primary advisor of the report belongs to an org that that is restricted _and_ the user is member of in any org belonging to the entire restricted hierarchy

### HMI:
Any org has :
- an indication of it's parent's restriction (if any). Example: this org (1.1.1) is a sub organization of the restricted org 1.1
- or an indication of a locally defined restriction. Example: this org restricts access to its members

### Db:
Each org has a "restricted" field which can be true or false, but has to be true if the parent's is true

### Pros: maybe easier to explain?
### Cons: may be trickier to deal when admins are modifingn restriction tree. Potentiallty not as flexible (access groups can't be nested)


## Case 3. Nested implicit restrictions, descending hierarchy

An engagement report is visible to the user if:
  - same first 3 cases as above
  - the primary advisor of the report belongs to an org that that is restricted _and_ the user is member of that org or one of its sub organizations

### HMI:
Any org has :
- an indication of it's parent's restriction (if any). Example: this org (1.1.1) is a sub organization of the restricted org 1.1
- or an indication of a locally defined restriction. Example: this org restricts access to its members

### Db:
Each org has a "restricted" field which can be true or false, but has to be true if the parent's is true

### Pros: maybe easier to explain?
### Cons: As soon as a sub-org is created in an already restricted org, it will not be visible to members of the parent orgs

**Comment by VassilIordanov** [comment]
Updated requirement:

The following approach is proposed:

Engagement report (all of them to start with) to have an optional field - "sensitive information"

The content of the field is only visible to:
- author
- attendees
- tbd

**Comment by maradragan** [comment]
This is what we decided to build:
- per organization, specify the list of positions (only positions from inside the org) who can see the sensitive part
- only admin users may change this list of positions
- author: sees sensitive info for his own reports
- others: see the sensitive info only if they belong to the list of positions

**Comment by gjvoosten** [comment]
Agreed plan of approach for sensitive information in reports:

• add table `reportsSensitiveInformation` with a text column of type `nvarchar(max)`
• ane one-to-one relationship between `reports` and `reportsSensitiveInformation`
• a report's sensitive information is only returned via the API if the user has permission (otherwise empty)
• a report's sensitive information can only be written via the API if the user has permission (otherwise ignored)
• a report's sensitive information is only shown (in display and edit forms) in the frontend if the user has permission (otherwise it would be empty anyway)

Permission set-up for sensitive information:

• add many-to-many `authorizedPositions` between `organizations` and `positions`
• only admins can edit the list of authorized positions for an organization

Permission to access sensitive information; either one of:

• user is the author of the report
• user currently holds a position that is in the list of `authorizedPositions` of the `advisorOrg` of the report

Audit trail:

• changes in `authorizedPositions` must be logged in the audit log
• changes to `reportsSensitiveInformation` must be logged in the audit log
• retrieves of `reportsSensitiveInformation` may be logged in the audit log

NOTE: do *not* log the sensitive information itself! only that it was inserted, updated (or retrieved) and by whom

And optionally add searching for sensitive information:

• add `reportsSensitiveInformation.text` column to full-text index
• column is only used in (full-text) searches if the user has permission (otherwise clause will not be added)
