### ISSUE TITLE
Upgrade selenium tests

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#175]
We should update tests/util/test.js with the following:
- replace selenium-webdriver with wd
- integrate browser stack (https://www.browserstack.com/automate/wd) (contact me for the access key)
- possibly improve how assertions work with chai
- configure so that we run the tests with IE11
- add a status badge to the front page (BS requested that so that they give us an opensource project plan) https://www.browserstack.com/automate/status-badges
- ~~if needed integrate with travis https://www.browserstack.com/automate/travisci~~

**Comment by gjvoosten** [comment]
Instead of replacing `selenium-webdriver`, let's look into:

- https://www.browserstack.com/automate/node
- https://www.browserstack.com/local-testing (with an extra setting as documented here: https://www.browserstack.com/automate/java#setting-local-tunnel )

so we don't need to change all our tests.

**Comment by gjvoosten** [comment]
Integration with Travis CI is split off into #211.
