### ISSUE TITLE
Screen goes blank after clicking the "Preview and submit" button on a draft report

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1886]
This bug has occurred three times in the last week.  An author clicks the "Preview and submit" button.  The screen goes blank.  The URL still has the word "edit" at the end of the URL.

When the author re-opens the draft report, the principals and efforts have disappeared.

I checked one report.  There are no records in the reportActions table and the reportTasks table for the report.  The reportPeople table only lists the authors record but not any principals.

I made myself the author of one these reports.

1. First submission: I was able to reproduce the error, i.e. blank screen; the efforts and principals had disappeared when I reopened the report

2. Second submission: The screen went blank again.  But when I re-opened the report, only the efforts disappeared.

3. Third submission: The screen went blank again.  When I re-opened the report, only the efforts had disappeared.

I also tried the following:
I refreshed the screen when the screen was blank.  The report reappeared in edit mode, but the efforts had disappeared.

I checked the report author and position.  They were both active.

clientLog.log - no reference to the author or report
auditLogger.log - entry for the report creation; nothing unusual found
anet-error.og - no reference to the author or report
anet.log - entry for the report creation; nothing unusual found
access.log - 114 references to the report; emailed a text file with the 114 lines to @VassilIordanov

**Comment by dspCarlson** [comment]
Here are the results of the IE11 console debugger:

Error Number: -2146827850
Message: Object doesn't support property or method "setSubmitting"

**Comment by maradragan** [comment]
Thank you @dspCarlson for the detailed description.

I think one of the following has happened:
1)
- the author has submitted the report
- the approvers have received an e-mail about approving the report
- the approver went to edit the report
- in the meanwhile he/she was removed from the approval step
- the approver clicked save and the window went blank 

2) the same, but than instead of the approver, the author did that, but he was no longer approver for the report

Anyway, this happens when the server throws an error, and that would for instance happen in one of the situations as above. It would return "You do not have permission to edit this report. Must be the current approver."

Client side we get an error when the server returns an error. I will try to fix that.

**Comment by dspCarlson** [comment]
This is a systemic problem.  I have had 11 emails and three phone calls today about this problem.  The emails are from all over and not just one advisor organization.
