### ISSUE TITLE
Epic 1705: Make the queries for recents a regular search

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#1952]
In the report form we now use the following queries to retrieve recents:
      locationRecents(maxResults:6) {
        list { uuid, name }
      }
      personRecents(maxResults:6) {
        list { uuid, name, rank, role, status, endOfTourDate, position { uuid, name, type, status, organization {uuid, shortName}, location {uuid, name} } }
      }
      taskRecents(maxResults:6) {
        list { uuid, shortName, longName, responsibleOrg { uuid, shortName} }
      }
      authorizationGroupRecents(maxResults:6) {
        list { uuid, name, description }
      }
      tagList(query:$tagQuery) {
        list { uuid, name, description }
      }

It would be nice to make this possible via the regular search, which would also make it possible to use the results just as other search results, having for instance the same way of paginating the results.

This is part of epic #1705

**Comment by gjvoosten** [comment]
If pagination is the issue, then perhaps just adding `pageNum`/`pageSize` support (to replace the `maxResults`) to the recents methods is a simpler solution. Otherwise the sorting of the results is going to be a problem. Now they are sorted "most recently used (by the current user, in a report) first"; with the search that will be far from trivial.

**Comment by maradragan** [comment]
Not only the pagination, it should also be able to filter the reports (for now at least by what is filled in the input field).
