### ISSUE TITLE
Advisor Profiles Created in the people Table without a Name

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#197]
Since 18 March 2017, there have been hundreds of advisor profiles automatically created with a:
1. blank name
2. status is new
3. email address is NULL
4. phone number is NULL
5. biography is NULL
6. role is an advisor
7. domain user name has a valid value
8. country is null
9. gender is null
10. end of tour is null

The profiles are created in all network domains.

On 6 September 2017, I deleted all of the records created since 18 March 2017.  That was 755 records.
As of 8 October 2017, there are now 168 of these records.  I suspect new users to Active Directory are automatically being inserted.

**Comment by dspCarlson** [comment]
On 8 November 2017, I deleted 282 of these records created since 6 September 2017.

**Comment by VassilIordanov** [comment]
We should look into can this happen if the user dismisses/does not complete the onboarding

**Comment by dspCarlson** [comment]
Doesn't the program make a call to active directory?  That's over 1,200 profiles created that look exactly alike.

Before every class I also delete these records.  Otherwise there is weird data for one of the exercises.

**Comment by dspCarlson** [comment]
@VassilIordanov Adrian Ganea found out how and when these ghost accounts are being created.  When someone (without a domain user name in the database) logs into the program, they are greeted with the create an account page.  Even though the person leaves the page without creating an account, a record is still inserted into the people table.

**Comment by gjvoosten** [comment]
The way the authentication backend currently works is: if a user correctly authenticates but does not yet exist in the database, a Person object is immediately created in the database; subsequently they are redirected to the onboarding process. Everything from that point on assumes that the Person object already exists in the database.

This means that the current behaviour is 'by design', and that the simplest remedy would probably be some form of _garbage collection_: periodically sweep the database and delete all Person objects older than X days with status `NEW_USER` (those would be the users that logged on but didn't complete the onboarding).

I did a quick investigation of the code, and while it would probably be possible to change the current behaviour to *not* create a new Person object *until* the onboarding process is completed (object validated and saved from the Create Profile page), it is non-trivial.
(E.g. creating a new person is currently only allowed by super users/admins; this would need to be changed to allow people to create 'themselves', as it were.)

**Comment by dspCarlson** [comment]
@VassilIordanov @gjvoosten There has been a work around for several months.  A job is run every hour from 0900 to 2000 that deletes these ghost accounts.  Since this job started, there have not been any more issues.

The job is called: Delete_ANET_Profiles_Automatically_Created
The stored procedure is called: DeleteNullPeople

**Comment by dspCarlson** [comment]
I am closing this issue and removing it from the feature project.  The execution of the hourly stored procedure eliminates this bug.
