### ISSUE TITLE
Change email address message

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#2081]
Change the current message from "Email address must be a valid email" to "Email address must be a valid classified email address"

Some advisors have five "valid" email addresses that they work.  Three email addresses on the low side and two on the high side.  The new message will at least clarify the type of email address to enter when this error message is displayed.

**Comment by maradragan** [comment]
From @VassilIordanov 
We can update the ticket to externalize the message in ANET.yml, each mission could then update appropriately

**Comment by maradragan** [comment]
- is this about the create person form, where one can fill in the e-mailaddress?
- we now only get the error "Email must be a valid email" when the e-mail format is not correct, so when someone types for instance only aa@@bb, so this is just a general error. Do we want to make this error ANET instance specific in order to be able to add the word classified to the message? I wouldn't think so.
- for NATO member email adresses, while the user is typing the e-mail address we check if it belongs to the whitelist of domains (whether we have a whitelist to check on depends on the ANET instance). Should we maybe always display a hint about the allowed domains?

**Comment by maradragan** [comment]
We decided that when the person is a NATO member, the email field would contain a placeholder coming from the ANET yml file.

**Comment by dspCarlson** [comment]
@maradragan This is a good solution.
