### ISSUE TITLE
Authentication in combination with Linux

### ISSUE THREAD

**Issue by jose-west** [NCI-Agency/anet#2314]
Since we want to move production to Linux, we want a replacement for Waffle. 

- [x] keycloak proof of concept
- [x] replace waffle in SPNEGO instances with keycloak 
- [x] investigate how to support Openid / SAML - natively or through keycloak

**Comment by nynymike** [comment]
Best practice is to support open standards for federated identity, like SAML and in particular (for requirements LOA 1 or 2), OpenID Connect (which has the security features which scale to LOA 4).  You could test against the [Gluu Server] (https://gluu.org/docs), which supports both standards. Also, be careful which client software to use. You might consider relying on [Apache](https://github.com/zmartzone/mod_auth_openidc) or [Nginx](https://github.com/zmartzone/lua-resty-openidc) to perform any required user authentication. Or you might want to consider using a middleware service like [oxd](https://oxd.gluu.org) to avoid a low-level protocol implementiation of the standard (even Gluu is doing this instead of implementing low level code in the app).

**Comment by midmarch** [comment]
This issue put on hold, as it requires change the default branch to the Linux version. Changing this at this point, would create issues keeping things in sync.
