### ISSUE TITLE
Force Report Author to Choose a Milestone/Task or Acknowledge a Milestone/Task was not Addressed

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#235]
Force report authors to either (1) choose one or more milestones/tasks for the engagement or (2) acknowledge milestones/tasks were not addressed during the engagement with the principal(s).

@gjvoosten @VassilIordanov Any ideas on how this could look? The business owners would like suggestions.

Business owners want to identify which engagements do not support the effort.

Reference item 107

**Comment by VassilIordanov** [comment]
I suggest that when a user is submitting a report without any poams PoAMs, a message appears stating something like: 
"You are about to submit a report that does not reference any PoAM. In order to submit your report, you are required to acknowledge that the engagement did not address a PoAM"
With 2 buttons below:
"I acknowledge no PoAM" and "Keep editing report"

**Comment by dspCarlson** [comment]
@VassilIordanov That's a good suggestion.  The absence of a PoAM assigned to a report will indicate the report author acknowledged not having a PoAM.

**Comment by VassilIordanov** [comment]
It was communicated by the users that this feature is desirable.
It also fits in the discussion of having both errors and warnings associated with actions on a page. 
In this case, not having a referenced tasks should result in:
- a warning (should not prevent a save action, but will prevent a submit)
- an error (should prevent a submit, unless acknowledged)
- an error (should prevent an approve, unless acknowledged)
not sure what to do with the acknowledged state, maybe we can get away with not persisting it anywhere.
