### ISSUE TITLE
Display Error Message When Deleting Report Approval Step and a Report is Still Pending

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#239]
When saving an advisor organization, a cryptic error message is sometimes displayed.  The current message states: "Not Acceptable: You do not have permissions to perform this action."  The error message comes from an approval step that has been removed that still has a pending report assigned to the approval step.

Improve the error message to let the super user know exactly what's wrong.  

Or even better, when the super user removes the approval step (with a pending report), display an error message and don't let the approval step be removed.  Display the error message when the report approval step is deleted instead of when the advisor organization is saved.

Reference item 104

**Comment by evdhoudt** [comment]
The issue seems to be a bit larger than simply displaying the error message.

Approval steps are not correctly loaded from the database:

When editing an organization: After adding a new approval step, the step does not show up in the list. At random when editing the approval steps, one or multiple steps do no show up.

@gjvoosten will look into the db specifics to figure out what is going wrong

**Comment by gjvoosten** [comment]
The erratic behaviour appears to have been caused by corrupt approval chains in the database (multiple approval steps with the same next step).The database has been manually corrected, and the code has been updated to wrap approval chain manipulation inside a database transaction to avoid future inconsistencies.
