### ISSUE TITLE
Implement a mode with disabled email

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#25]
Provide the ability to disable email notifications (temporarily or for test deployments)

**Comment by gjvoosten** [comment]
Since the stacktraces about "Unknown SMTP host: ${ANET_SMTP_SERVER}" are quite annoying and clutter up the logs while developing (and make stuff less readable/obvious), I propose to move this one forward to e.g. the first Sprint.
I already have some code in my development environment to reduce the amount of logging in this case (in case of UnknownHostException just print the message instead of the whole stacktrace), but a config option to switch off emailing altogether is preferable, and not too hard to do.

**Comment by gjvoosten** [comment]
One has to admire the coincidence of this SMTP issue having number 25 ✉️ 
```fgrep -w 25 /etc/services```
