### ISSUE TITLE
Do Not Allow Report Authors to Create Reports When Their Assigned Advisor Position Has an Inactive Status

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#264]
Prevent report authors from creating reports when their advisor position's status is inactive.

When the report author selects the "New report" button, display a message for the advisor to contact their super user to set the position status to active.

Do not let the report author create an engagement report.

Reference item 116

**Comment by evdhoudt** [comment]
@VassilIordanov  @dspCarlson Should report authors with an inactive status be allowed to create a Draft report?

At the moment, users without an assigned position, are allowed to create a draft report.

Is this the required behavior?
* Users with an assigned position and active status are allowed to submit (create) a report
* Users without an assigned position or an inactive status are allowed to save a draft report
** (In both cases a message is displayed to contact the 'support team' [instead of the wording superuser] 

For example the messages could be:
1. You do not have an assigned position please contact the support team (email@example.com) and request a position
2. You do not have an active position, please contact the support team (email@example.com) and request to set your position status to active

**Comment by VassilIordanov** [comment]
I think that _anyone_ should be allowed to create draft reports. Submitting them is when most checks should occur

**Comment by evdhoudt** [comment]
For the record, users are allowed to create draft versions of the report. 
- Submitting the report is NOT allowed. 
- A warning is always displayed when a user does not have an active position
