### ISSUE TITLE
Add an ANET service graphql interface

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3019]
Add an ANET service interface with the following methods:
`anetVersion` - returns the version of ANET served by the server, visible to all users
`clearCache` - clears all caches, mutation allowed for admins only
`reload dictionary` - reloads the dictionary (may requiure splitting the dictionary from the rest of the `anet.yml` file), mutation allowed for admins only
`recentUsers` - returns the users that recently called a service, last time of service use (besides heartbeats) and ip address (either users in the last n minutes, or the most recent n users...)

**Comment by oayvazoglusim** [comment]
* anet version : it says version of Anet served by the server . I guess this is the version that "git describe" returns , isn't it ?
* clearCache : Does it mean to server side cache of working project on network or is it the cache just only related with the admin's client-side cache (Apollo cache logic)
* reload dictionary : What I understand on this subject is ; a network admin changes the dictionary file located in deployed project folder manually (which will be a seperate file other than anet.yml)  and then wants to apply these new dictionary values into to the working project instance without restarting server.
So he/she needs a service url to reload AnetConfiguration dictionary parameter with these new values .Does the scenario like that or did I get it wrong?

* Last question is about UI .
is it just enough to create new call urls so that admin calls these urls manually to clearCache and reloadDictionary 
or should we provide a new UI page and so admin opens that page and can trigger these functions through clicking buttons (Clear Cache and Reload Dictionary) placed on that page.

**Comment by VassilIordanov** [comment]
>    anet version : it says version of Anet served by the server . I guess this is the version that "git describe" returns , isn't it ?
I think this is a good one to use. At gradlew build time, we can inject this version in `index.hsb` or similar, as well as somewhere in the server-side code as well.

>    clearCache : Does it mean to server side cache of working project on network or is it the cache just only related with the admin's client-side cache (Apollo cache logic)
As it is a graphql service, it is about serverside cache. I had in mind to clear the `ehcache` cache, but there could be others. Which one did you have in mind?

>    reload dictionary : What I understand on this subject is ; a network admin changes the dictionary file located in deployed project folder manually (which will be a seperate file other than anet.yml) and then wants to apply these new dictionary values into to the working project instance without restarting server.
>    So he/she needs a service url to reload AnetConfiguration dictionary parameter with these new values .Does the scenario like that or did I get it wrong?
Correct. We are looking to reload the new values in the service that returns the dictionary. We should not try to solve updating the clients's states with these values, as this is probably too much work at this point

>    is it just enough to create new call urls so that admin calls these urls manually to clearCache and reloadDictionary
>    or should we provide a new UI page and so admin opens that page and can trigger these functions through clicking buttons (Clear Cache and Reload Dictionary) placed on that page.
Let's put them directly in the existing page for `/admin`:
clearCache -> a button there
recentUsers/onineUsers -> a simple react table

anet version -> we can put this in the banner, visible to everyone
