### ISSUE TITLE
Multiple authors of report

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3215]
Since we focus on planning engagements the following scenario has started to emerge:

- Person 1 plans an engagement. I has Person 2 as primary advisor and Person 3 in attendance.
- The engagement happens
- Person 3 is supposed to document the engagement, but has no access and has no notification of that.

We should explore ways to handle such situations, including:
- possibly give write access to all attendees
- for future engagements, allow the planner to designate a "minute taker"

**Comment by VassilIordanov** [comment]
I am tempted to suggest to add the ability to have multiple authors:
- Person drafting a report (future or past) for the first time is added as author by default
- authors are an attendance table attribute such as `primary`
- all authors get write access
- all authors get email notifications.... 
- the confusing part could be how to handle change requests, possibly having only the submitter getting the notifications...

**Comment by gjvoosten** [comment]
Also be aware of more than one author simultaneously editing/saving the same report.

**Comment by cemalettin-simsoft** [comment]
Can we assume "multiple people editing the same report at the same time" will not happen? Otherwise, we probably need to implement some sort of lock for the report when someone starts editing / unlock when editing is done.

To prevent that, we can put some warnings if a report has multiple authors saying "Be sure to coordinate with other authors when editing, do not edit at the same time".
