### ISSUE TITLE
New task structure

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#323]
The following changes to PoAMs are proposed:
1. Internally to the code, rename/refactor PoAM to Task. 
1. Add the following fields to Tasks
    - Projected Completion (of type Date)
    - Planned Completion (of type Date)
    - Custom field (String, to be named in dictionary and used to map to an external ID)
    - Status (enum, possible choices to be defined in dictionary. To be used later as Kanban-type tracking)

**Comment by evdhoudt** [comment]
Refactor PoAM to Task. I'll perform the refactor according to the following workflow:
- [x] Refactor front end UI 
- [ ] Refactor GraphQL
- [ ] Refactor DAO and Resources
- [ ] Refactor server side models and DB scheme

**Comment by VassilIordanov** [comment]
@evdhoudt It is also needed to integrate the new task fields into the search, both in the general search as well as adding the fields as custom search parameters

**Comment by VassilIordanov** [comment]
moving to doing - still needs advanced and full text search

**Comment by evdhoudt** [comment]
@VassilIordanov Added the fields to the advanced and full text search. 

I have NOT added the custom field to its own specific search filter/ It felt somewhat unnecessary since the custom field is added to the full text search, users are able to find the correct task by simple adding the search term to the search bar.
