### ISSUE TITLE
1,332 blank reports created by report author in less than 12 hours

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#3250]
**Describe the bug**
2020-09-29 15:08:04.610 Report author creates a report

After the initial report was created by the report author, 1,332 blank reports were created.
2020-09-29 15:30:33.644 First blank report created
2020-09-30 03:02:55.415 Last blank report created

**To Reproduce**
Unknown

**Expected behavior**
Blank reports should not be automatically created

**Screenshots**
N/A

**Environment (please complete the following information):**
Unknown

**Additional context**
The clientLog-2020-09-30.log file has two error records from the report author: Unable to get property 'match' of undefined or null reference

In the auditLogger files for 29 September and 30 September, there are some gibberish records.  The records are long but don't seem to make any sense.  One record alone is 2,363 characters (with spaces).  However, these long, gibberish records do not have the report authors uuid.  Maybe this is another problem.

**Comment by cemalettin-simsoft** [comment]
I suggest we close this issue until we find a way to reproduce it or encounter again. As a last note what i can say about this issue is:

1. Could be related to server restart and having stuck in an inconsistent state. The timing  and exact details of the user actions needed to reproduce this error.
2. Could be related to version of MS Edge
3. Could be combination of both

If it survives long enough, more context here: https://nci-agency.slack.com/archives/C67NG1BC1/p1602941124239500

**Comment by dspCarlson** [comment]
@cemalettin-simsoft I agree this issue should be closed.  This bug has happened before, but a long time ago.
