### ISSUE TITLE
Sensitive information permission phase II

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#328]
Sensitive information permissions should be extended to:
- permit designated positions beyond the org positions to see the sensitive information.

It is suggested to do so by:
- Admins maintain a global set of named groups/lists of positions (positions could be across organizations). When displaying/editing a group, the following should be visible:
    - group name
    - list of positions, displaying 'name of incumbent, position name, org name'  sorted by org name first. 
- Report authors, when entering sensitive information, are prompted to select one or more groups with which to share the sensitive information. The groups with which it is shared remain editable until the report is published when it becomes read-only as the rest of the report. Frequently used groups should be suggested to the user. It will be good if the user can preview the group(s) membership by clicking on it.

It is also suggested to add an active/inactive (or whatever is the exact wording in other parts of ANET) property to groups. If a group is inactive, it can still be used to authorize access, but new reports sensitive info can't be assigned to it - and not available in autosuggest. This is seen as possible solution to manage clutter in the future.

**Comment by maradragan** [comment]
These are the tasks we could identify for this issue:
- implement datamodel
- add test data for authorized groups
- update add/edit form of a report to allow adding authorized groups (first simple search on authorized groups by name)
- implement new permission checks for sensitive information
- add migration scripts for the current reports having sensitive information
- update the manage authorized groups interface on a report: make it more fancy, like a more complex search, allow preview of the groups)
- add manage authorized groups admin part, in order to list and add/view authorized views

**Comment by VassilIordanov** [comment]
updated with active/inactive status for groups

**Comment by maradragan** [comment]
In order to improve the maintenance of authorization groups we should also do the following:
- on the authorization group details page, show the list of related reports
- add tests for the admin pages
- add user documentation

**Comment by VassilIordanov** [comment]
We should make it not possible to submit a report if there is sensitive info entered but no authorized groups.
