### ISSUE TITLE
Fix insights & rollup pages rendering half of the page

### ISSUE THREAD

**Issue by cemalettin-simsoft** [NCI-Agency/anet#3282]
**Describe the bug**
Insights pages render half of the page , also it renders full page when the insights dropdown opens. This is the current behavior:
![insights-page](https://user-images.githubusercontent.com/69463668/98345700-12220e80-2026-11eb-880d-f536118559c5.gif)

**To Reproduce**
1. Go to 'home page as admin'
2. Click on 'insights dropdown from navigation and select an item from the dropdown'
3. Page is shown half
4. Open-close the dropdown to see the effect

**Expected behavior**
Page should be shown fully on first landing and shouldn't change with dropdown opening-closing

**Environment (please complete the following information):**
 - Chrome 86 / Linux

**Additional Information**
- Tested on latest firefox, it works as expected. So the issue appears on Chrome but not Firefox.

**Comment by gjvoosten** [comment]
Going back to the code on `candidate` from a year ago (tag 2.1.15, commit 28d4e7e6f1a61f19bb44652f821657dd55b34dca), the problem is there as well, which leads me to believe the problem lies with Chrome and not so much our code. And sure enough, when testing this on BrowserStack I see the problem with Chrome 86 but not with Chrome 85. I also see the problem wtih Chrome 87 Beta and with Chrome 88 Dev, so it may warrant further investigation (although I don't believe our current, actual _users_ use Chrome, but anyway).

**Comment by gjvoosten** [comment]
The Daily Rollup has the same problem.
