### ISSUE TITLE
Report bounced back to draft after submission

### ISSUE THREAD

**Issue by midmarch** [NCI-Agency/anet#3304]
**Description**
After report submission the user receives an a-mail:

> The date of your upcoming engagement into a draft report. You can find and edit it by going to the "My drafts" on the "My reports" page, by clicking here.
> 
> ANET Support team

which is requesting the user to re-submit the report.

**Expected behavior**
The report is not ending up as draft after submission without a clear issue.

**Comment by gjvoosten** [comment]
This is due to an error in the logic that changes future (planned) engagements that have been submitted (i.e. are in the planning workflow) to current engagements when the date has come. If the author then completes the report and submits it for processing through the regular approval workflow, the next run of the FutureEngagementWorker will change the report back to draft again.
