### ISSUE TITLE
NPE in the log

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#407]
There are null pointer exceptions generated on this line:
https://github.com/NCI-Agency/anet/blob/2.0.8/src/main/java/mil/dds/anet/resources/ReportResource.java#L198
This happen because some computers start issuing bad requests exactly every 30 seconds. At first I thought it is some crawler or some other kind of robot. Now it looks to me it that it is a bug in the client making the autosave initiate wrong requests. 
All requests are logged as "POST /api/reports/update?sendEditEmail=false HTTP/1.1" 500 110 "http://<server_name_edited>/reports/new" "Mozilla 4.0....
I have not looked at the autosave code yet. Any ideas how this could happen?

**Comment by gjvoosten** [comment]
A reproducible scenario is:
* create new report
* fill in some field and wait for autosave
* in another browser (window) go to your draft reports, and delete the just-autosaved draft report
* in the previous browser (window), change something to the autosaved report and wait for autosave
* this tries to update a report with an id that no longer exists, and throws an NPE on the indicated code line

Since this scenario cannot realistically be prevented, we'll address this instead by doing exponential back-off if the autosave fails, to prevent cluttering the logs with messages every 30 seconds.
