### ISSUE TITLE
Report Approver Email Lacks Approvers Name

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#459]
The email sent to report approvers doesn't have the report approver's name.

The first line looks like this: Dear ,

**Comment by maradragan** [comment]
Reaction from @gjvoosten :+1: There is a single email, sent to the email addresses of all approvers of the current approval step, with the heading:
_Dear <approvalStepName>,_
which could be for example:
*Dear EF 2.2 Initial Approvers,*

If there is no text after *Dear*, that would mean that either the current approval step has no name (unusual, since there's normally no way to have a step without a name), or there is no current approval step (odd, not sure how that could happen, maybe a sequence of events similar to the one that led to the situation in https://github.com/NCI-Agency/anet/issues/726 ?).

**Comment by maradragan** [comment]
Answer from @dspCarlson : I only noticed the salutation missing when I happened to be at a user's desk so this issue was not a complaint from a user.  I don't have any access to these emails since I am not assigned to an approval step.  Let's let GH-459 wait for now.

**Comment by dspCarlson** [comment]
@maradragan I created and submitted a report today.  Since I approve reports for my organization, I received an approver email.  The email no longer has the word "Dear" in it.  The email is understandable and user friendly.

I am closing this issue.
