### ISSUE TITLE
Include Pagination at the Bottom of Report Collections

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#514]
Users scroll down through 10 results.  Then if they want to see more search results, they must scroll to the top of the search results and choose the next page.

(copied from #516)
Also, if the daily roll up returns more than 10 reports, the user must scroll to the top of the reports to select the next page.
Today a user requested pagination also be included at the bottom of daily roll up reports.

**Comment by gjvoosten** [comment]
@dspCarlson Any report collection (not just when shown in the search or daily rollup) would probably benefit from having pagination at the bottom as well as at the top. This includes e.g. insights, my reports, etc. Since it is a common component to all of these, making the change there seems most useful.

I'll update the title and description, and close #516 as duplicate.
