### ISSUE TITLE
Difference Results for Advanced Search and Saved Search

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#517]
The Advanced search was:
Button: Reports
Filter: Attendee Position (an advisor position)
Filter: Release Date - Last 7 days

The Advanced search returned no reports.

The user saved the Advanced search.

The user went to their dashboard and selected the saved search just created.

The saved search returned reports beyond the "Last 7 days."

**Comment by gjvoosten** [comment]
It appears the _Release date_ filter is not correctly saved, which can be seen as follows:

- go to the home page
- click _Advanced search_
- click _Add another filter_
- pick the *Release Date* filter
- pick *Last 7 Days*
- click _Search_

You are shown the search results page, with the filter at the top; however, the *Release Date* filter just shows *Between DD/MM/YYYY and DD/MM/YYYY* instead of *Last 7 Days*.

If, in this form, you then change the *Release Date* filter again to *Last 7 Days* and click _Search_, the filter shows correctly. If you now save the search, the filter is correctly saved as well.
