### ISSUE TITLE
Authentication module

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#619]
Add:
- [x] the ability to identify people based on more than one identity (i.e. several domain usernames, mix of accounts below)
- [x] the ability to authenticate through either:
  - windows authentication as currently implemented
  - an established standard (i.e. OAuth 2.0, OpenID ...)
- [x] UI to allow users to chose (when applicable) between Windows single sign-on, local account sign-in/ creation or delegation to 3rd party identity providers
- [ ] update public demo/training server to use delegation to public cloud identity providers

**Comment by nynymike** [comment]
Best practice is to support open standards for federated identity, like SAML and in particular (for requirements LOA 1 or 2), OpenID Connect (which has the security features which scale to LOA 4).  You could test against the [Gluu Server] (https://gluu.org/docs), which supports both standards. Also, be careful which client software to use. You might consider relying on [Apache](https://github.com/zmartzone/mod_auth_openidc) or [Nginx](https://github.com/zmartzone/lua-resty-openidc) to perform any required user authentication. Or you might want to consider using a middleware service like [oxd](https://oxd.gluu.org) to avoid a low-level protocol implementiation of the standard (even Gluu is doing this instead of implementing low level code in the app).

**Comment by gjvoosten** [comment]
Keycloak has the ability to add identity brokers: https://www.keycloak.org/docs/latest/server_admin/index.html#_identity_broker
so https://github.com/NCI-Agency/anet/pull/3217 would go a long way towards addressing this.
