### ISSUE TITLE
Missing key strokes when using ANET search data fields

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#767]
When typing in any data field that has the magnifying glass/search icon, key strokes will be missed.

**Comment by VassilIordanov** [comment]
I was looking at this but I do think that this is happening: https://github.com/moroshko/react-autosuggest/issues/494
It seems to me that on some keystrokes onInputChange is not invoked

**Comment by VassilIordanov** [comment]
it seems like it is happening as the bug in react has been reintroduced in 16.4.1: https://github.com/facebook/react/issues/7027

**Comment by gjvoosten** [comment]
In my experiments, occasionally keystrokes were dropped while the list of retrieved suggestions is being rendered. When retrieving 250 suggestions instead of the normal 25, this was slightly more often the case.
I've made some changes to the autocomplete state handling and the suggestion rendering that (at least in my experiments) made the dropping of keystrokes quite rare. But we'll just have to see whether this helps.
Note that only IE11 would drop keystrokes; I was unable to get either Firefox or Chrome do that.

**Comment by dspCarlson** [comment]
This annoying bug is fixed!
